{
  "id": 8,
  "title": "CSGO MOVES & RUMORS BEFORE THE NEW YEAR – MAJOR ROSTER SHUFFLES COMING",
  "subtitle": "Ahhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh Victory",
  "text": "There are many still rumored yet to be confirmed. Amongst the most interesting rosters that are changing is Team Liquid. The \r\n\tonce powerhouse North American team has fallen to new lows with their current roster. A massive shuffle is needed and that’s \r\n\texactly what they are doing.\n\r\n\tTHE CONFIRMED\n\r\n\tLiquid has confirmed a few big changes so far. They have officially announced the removal of FalleN, Stewie2K and Grim from \r\n\ttheir starting lineups. Two of the three rumored signings have proven to be true. oSee, who got his big break on HenryG’s \r\n\tCloud9 roster, has now signed with TL. oSee has been showing good numbers in tier 2 playing on Extra salt, and has impressed \r\n\this peers in online ladder play. He will fill the role of AWPer, which TL has had a hard time filling with this past roster \r\n\twith players passing the role back and forth.\n\r\n\tThe other big Liquid signing is shox. Though he has performed on an average level the last little while, he could be a good fit \r\n\tfor a support role à-la xyp9x, with his icy veins under pressure in the clutch. He is still one of the best players in the world \r\n\ton LAN in 1vX situations. Since he is 29, he has been in every situation imaginable and has the tendency to make great plays. If \r\n\tthis is his last run on a tier 1 team, this is a good role for him to have. He may no longer have what it takes to be a star \r\n\tplayer, but he has the knowledge and experience to contribute. This is the natural progression of a star CSGO player.\n\r\n\tOver in Europe, Torbjørn “mithR” Nyborg departed MOUZ for a coaching gig at Apeks. Unicorns of Love, sAw and Into \r\n\tthe Breach all released their rosters, with everyone seeking to re-build at the start of the year.\n\r\n\tTHE SPECULATION\n\r\n\tRecently, 100 Thieves announced that they would be transferring nitr0 to an unknown team. After more than a year out of the game, \r\n\the will be likely returning to CSGO and potentially TL? EliGE continues to speak highly of him, saying he wants Nitro as his IGL. \r\n\tNitro was on Team Liquid during their peak when they won the Grand Slam back in 2019. TL would have been the best team in the \r\n\tworld if it hadn’t been for the greatest team of all time, Astralis. I’m sure somewhere in the back of his mind Nitro thinks he \r\n\tcan get the team back to the heights at which they once were.\n\r\n\tMeanwhile, MOUZ is looking at OG’s Valdemar Bjørn Vangså for their roster into the upcoming season. Astralis is rumored to be \r\n\tlooking at Heroic talent for their roster revamp. Plenty of teams are holding the cards close to their chest, and more “leaks” \r\n\tshould arrive in the second week of January.\n\r\n\tUntil then, happy new year and brace for a hectic CSGO offseason.",
  "publication_date": "2021-12-21",
  "cover_img": "csgo-valde.jpg",
  "read_time": 5,
  "is_approved": 0,
  "author": "matteocasonato"
}